[package]
name = "forecast-rust"
version = "0.1.0"
edition = "2021"
rust-version = "1.82"

[dependencies]
askama = "0.12.1"
axum = "0.7.7"
reqwest = "0.12.9"
sea-orm = { version = "1.1.0", features = ["sqlx-sqlite", "runtime-tokio-native-tls", "macros"] }
serde = "1.0.214"
serde_json = "1.0.132"
thiserror = "2.0.1"
tokio = "1.41.0"
tower = "0.5.1"
tower-http = "0.6.1"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"

[dev-dependencies]
sea-orm-cli = { version = "1.1.0", features = ["runtime-tokio"] }

[workspace]
members = [
    ".",
    "migration"
]