[build]
rustflags = ["-D", "warnings"]

[target.'cfg(all())']
rustflags = [
    "-D", "clippy::all",
    "-D", "clippy::pedantic",
    "-A", "clippy::missing-errors-doc",
    "-A", "clippy::missing-panics-doc",
]